### Create Employee
POST http://localhost:3000/employee/create
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "mobile":456789098765,
  "designation": "Developer",
  "companyname":"AWS"
}

###
GET http://localhost:3000/employee/read

###
PUT http://localhost:3000/employee/edit
Content-Type: application/json

{
  "name": "Jaya Dewa",
  "companyname": "Amazon"
}

###
DELETE http://localhost:3000/employee/delete/john@example.com